---
- name: Update, Upgrade, and Cleanup Packages, then Check if Reboot is Needed
  hosts: all
  become: true
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Autoremove unnecessary packages
      ansible.builtin.apt:
        autoremove: yes
        purge: yes

    - name: Check if a reboot is required
      ansible.builtin.command:
        cmd: test -f /var/run/reboot-required
      register: reboot_status
      failed_when: false
      changed_when: false

    - name: Debug reboot status
      ansible.builtin.debug:
        var: reboot_status

    - name: Report reboot status
      ansible.builtin.debug:
        msg: "Reboot required"
      when: reboot_status is defined and reboot_status.rc == 0

    - name: Report no reboot required
      ansible.builtin.debug:
        msg: "No reboot required"
      when: reboot_status is defined and reboot_status.rc != 0
