---
- name: Update, Upgrade, and Cleanup Packages, then Check if Reboot is Needed
  hosts: all
  become: true
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Autoremove unnecessary packages
      ansible.builtin.apt:
        autoremove: yes
        purge: yes

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    
    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true
